In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv("/content/Apple_historical_data.csv")
df

,Date,Open,High,Low,Close,Volume,ticker,name
0,1980-12-12 00:00:00-05:00,0.098389,0.098817,0.098389,0.098389,469033600,AAPL,Apple Inc. (AAPL) Historical Data
1,1980-12-15 00:00:00-05:00,0.093684,0.093684,0.093256,0.093256,175884800,AAPL,Apple Inc. (AAPL) Historical Data
2,1980-12-16 00:00:00-05:00,0.086839,0.086839,0.086412,0.086412,105728000,AAPL,Apple Inc. (AAPL) Historical Data
3,1980-12-17 00:00:00-05:00,0.088550,0.088978,0.088550,0.088550,86441600,AAPL,Apple Inc. (AAPL) Historical Data
4,1980-12-18 00:00:00-05:00,0.091118,0.091545,0.091118,0.091118,73449600,AAPL,Apple Inc. (AAPL) Historical Data
...,...,...,...,...,...,...,...,...
11350,2025-12-24 00:00:00-05:00,272.339996,275.429993,272.200012,273.809998,17910600,AAPL,Apple Inc. (AAPL) Historical Data
11351,2025-12-26 00:00:00-05:00,274.160004,275.369995,272.859985,273.399994,21521800,AAPL,Apple Inc. (AAPL) Historical Data
11352,2025-12-29 00:00:00-05:00,272.690002,274.359985,272.350006,273.760010,23715200,AAPL,Apple Inc. (AAPL) Historical Data
11353,2025-12-30 00:00:00-05:00,272.809998,274.079987,272.279999,273.079987,22117600,AAPL,Apple Inc. (AAPL) Historical Data
11354,2025-12-31 00:00:00-05:00,273.049988,273.679993,271.760010,272.700104,7547237,AAPL,Apple Inc. (AAPL) Historical Data

In [15]:
print (df.head())

                        Date      Open      High       Low     Close  \
0  1980-12-12 00:00:00-05:00  0.098389  0.098817  0.098389  0.098389
1  1980-12-15 00:00:00-05:00  0.093684  0.093684  0.093256  0.093256
2  1980-12-16 00:00:00-05:00  0.086839  0.086839  0.086412  0.086412
3  1980-12-17 00:00:00-05:00  0.088550  0.088978  0.088550  0.088550
4  1980-12-18 00:00:00-05:00  0.091118  0.091545  0.091118  0.091118

      Volume ticker                               name
0  469033600   AAPL  Apple Inc. (AAPL) Historical Data
1  175884800   AAPL  Apple Inc. (AAPL) Historical Data
2  105728000   AAPL  Apple Inc. (AAPL) Historical Data
3   86441600   AAPL  Apple Inc. (AAPL) Historical Data
4   73449600   AAPL  Apple Inc. (AAPL) Historical Data

In [16]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11355 entries, 0 to 11354
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    11355 non-null  object
 1   Open    11355 non-null  float64
 2   High    11355 non-null  float64
 3   Low     11355 non-null  float64
 4   Close   11355 non-null  float64
 5   Volume  11355 non-null  int64
 6   ticker  11355 non-null  object
 7   name    11355 non-null  object
dtypes: float64(4), int64(1), object(3)
memory usage: 709.8+ KB
None

In [17]:
df = df.dropna()
df = df.drop_duplicates()
df

,Date,Open,High,Low,Close,Volume,ticker,name
0,1980-12-12 00:00:00-05:00,0.098389,0.098817,0.098389,0.098389,469033600,AAPL,Apple Inc. (AAPL) Historical Data
1,1980-12-15 00:00:00-05:00,0.093684,0.093684,0.093256,0.093256,175884800,AAPL,Apple Inc. (AAPL) Historical Data
2,1980-12-16 00:00:00-05:00,0.086839,0.086839,0.086412,0.086412,105728000,AAPL,Apple Inc. (AAPL) Historical Data
3,1980-12-17 00:00:00-05:00,0.088550,0.088978,0.088550,0.088550,86441600,AAPL,Apple Inc. (AAPL) Historical Data
4,1980-12-18 00:00:00-05:00,0.091118,0.091545,0.091118,0.091118,73449600,AAPL,Apple Inc. (AAPL) Historical Data
...,...,...,...,...,...,...,...,...
11350,2025-12-24 00:00:00-05:00,272.339996,275.429993,272.200012,273.809998,17910600,AAPL,Apple Inc. (AAPL) Historical Data
11351,2025-12-26 00:00:00-05:00,274.160004,275.369995,272.859985,273.399994,21521800,AAPL,Apple Inc. (AAPL) Historical Data
11352,2025-12-29 00:00:00-05:00,272.690002,274.359985,272.350006,273.760010,23715200,AAPL,Apple Inc. (AAPL) Historical Data
11353,2025-12-30 00:00:00-05:00,272.809998,274.079987,272.279999,273.079987,22117600,AAPL,Apple Inc. (AAPL) Historical Data
11354,2025-12-31 00:00:00-05:00,273.049988,273.679993,271.760010,272.700104,7547237,AAPL,Apple Inc. (AAPL) Historical Data